services:
  postgres:
    image: postgres:16
    container_name: scout_postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: scans
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: scout_redis
    ports:
      - "6379:6379"

  neo4j:
    image: neo4j:5
    container_name: scout_neo4j
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7474:7474" # HTTP UI
      - "7687:7687" # Bolt connection
    volumes:
      - neo4jdata:/data

volumes:
  pgdata:
  neo4jdata:
